development:
  adapter: postgresql
  encoding: unicode
  database: dashboard_development
  pool: 5
  username: fedex
  password: fedex
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: dashboard_test
  pool: 5
  username: fedex
  password: fedex
  min_messages: warning